http://localhost:5000/students

###
http://localhost:5000/students/a8ac50a2-0dae-4df2-9d90-61e593c1c337

###
POST  http://localhost:5000/students HTTP/1.1
content-type: application/json

{
    "fname": "Albert",
    "lname": "Hitchcock",
    "grade": "C"
}

###

DELETE http://localhost:5000/students/003


###
PATCH  http://localhost:5000/students/002 HTTP/1.1
content-type: application/json

{
    "fname": "Albertoo",
    "lname": "Hitchcock",
    "grade": "B"
}